spring.application.name=similar-products
server.port=5000

# Enables Java 21 Virtual Threads automatically when running on JDK 21+
spring.threads.virtual.enabled=true

product.api.base-url=http://localhost:3001
product.api.timeout-ms=2000

